include: package:very_good_analysis/analysis_options.2.3.0.yaml

linter:
  rules:
    public_member_api_docs: false
    cascade_invocations: false
    avoid_dynamic_calls: false
    sort_pub_dependencies: false