name: kspm_scheduler_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  collection: ^1.16.0
  connectivity_plus: ^2.2.0
  dartz: ^0.10.1
  device_info_plus: ^4.0.0
  dio: ^4.0.4
  easy_pdf_viewer: ^1.0.2
  equatable: ^2.0.3
  file_picker: ^5.0.1
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.6
  firebase_messaging: ^12.0.0
  fluentui_system_icons: ^1.1.153
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.2.0
  flutter_svg: ^1.1.3
  form_field_validator: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.11
  rxdart: ^0.27.4
  sentry_flutter: ^6.6.3
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  varx_design_system: ^0.2.8

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_driver:
    sdk: flutter
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.3
  mockito: ^5.0.17
  mocktail: ^0.3.0
  network_image_mock: ^2.0.1
  very_good_analysis: ^3.0.1
  analyzer: ^4.2.0

dependency_overrides:
  meta: ^1.7.0
  provider: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
