name: kspm_scheduler_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  connectivity_plus: ^2.2.0
  dartz: ^0.10.1
  device_info_plus: ^3.2.1
  device_preview: ^1.1.0
  dio: ^4.0.4
  equatable: ^2.0.3
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  fluentui_system_icons: ^1.1.153
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_sheet_localization: ^5.1.1
  form_field_validator: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  rxdart: ^0.27.4
  sentry_flutter: ^6.6.3
  shared_preferences: ^2.0.11

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^5.1.7
  json_serializable: ^6.1.3
  very_good_analysis: ^2.4.0

dependency_overrides:
  analyzer: ^2.6.0
  meta: ^1.7.0
  provider: ^6.0.0

flutter:
  uses-material-design: true
